BEGIN TRANSACTION
SET QUOTED_IDENTIFIER ON
SET ARITHABORT ON
SET NUMERIC_ROUNDABORT OFF
SET CONCAT_NULL_YIELDS_NULL ON
SET ANSI_NULLS ON
SET ANSI_PADDING ON
SET ANSI_WARNINGS ON
COMMIT
BEGIN TRANSACTION
GO
ALTER TABLE GRUPO_N.Cupon ADD
	Codigo nvarchar(50) NOT NULL
GO
CREATE UNIQUE NONCLUSTERED INDEX IX_Cupon_Codigo ON GRUPO_N.Cupon
	(
	Codigo
	) WITH( STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX IX_Cupon_FechaPublicacion ON GRUPO_N.Cupon
	(
	FechaPublicacion
	) WITH( STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX IX_Cupon_FechaVigencia ON GRUPO_N.Cupon
	(
	FechaVigencia
	) WITH( STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO
EXECUTE sp_rename N'GRUPO_N.Cupon.FechaVencimmiento', N'Tmp_FechaVencimiento', 'COLUMN' 
GO
EXECUTE sp_rename N'GRUPO_N.Cupon.Tmp_FechaVencimiento', N'FechaVencimiento', 'COLUMN' 
GO
ALTER TABLE GRUPO_N.Cupon SET (LOCK_ESCALATION = TABLE)
GO
COMMIT
