/* Para evitar posibles problemas de pérdida de datos, debe revisar este script detalladamente antes de ejecutarlo fuera del contexto del diseñador de base de datos.*/
BEGIN TRANSACTION
SET QUOTED_IDENTIFIER ON
SET ARITHABORT ON
SET NUMERIC_ROUNDABORT OFF
SET CONCAT_NULL_YIELDS_NULL ON
SET ANSI_NULLS ON
SET ANSI_PADDING ON
SET ANSI_WARNINGS ON
COMMIT
BEGIN TRANSACTION
GO
ALTER TABLE GRUPO_N.Proveedor
	DROP CONSTRAINT FK_Proveedor_DetalleEntidad
GO
ALTER TABLE GRUPO_N.Direccion
	DROP CONSTRAINT FK_Direccion_DetalleEntidad
GO
ALTER TABLE GRUPO_N.Ciente
	DROP CONSTRAINT FK_Ciente_DetalleEntidad
GO
DROP INDEX IX_DetalleEntidad ON GRUPO_N.DetalleEntidad
GO
CREATE UNIQUE NONCLUSTERED INDEX IX_DetalleEntidad ON GRUPO_N.DetalleEntidad
	(
	Telefono
	) WITH( STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO
ALTER TABLE GRUPO_N.DetalleEntidad SET (LOCK_ESCALATION = TABLE)
GO
COMMIT
BEGIN TRANSACTION
GO
ALTER TABLE GRUPO_N.Direccion ADD CONSTRAINT
	FK_Direccion_DetalleEntidad FOREIGN KEY
	(
	ID_Detalle
	) REFERENCES GRUPO_N.DetalleEntidad
	(
	ID
	) ON UPDATE  NO ACTION 
	 ON DELETE  NO ACTION 
	
GO
ALTER TABLE GRUPO_N.Direccion SET (LOCK_ESCALATION = TABLE)
GO
COMMIT
BEGIN TRANSACTION
GO
ALTER TABLE GRUPO_N.Proveedor ADD CONSTRAINT
	FK_Proveedor_DetalleEntidad FOREIGN KEY
	(
	ID_Detalle
	) REFERENCES GRUPO_N.DetalleEntidad
	(
	ID
	) ON UPDATE  NO ACTION 
	 ON DELETE  NO ACTION 
	
GO
ALTER TABLE GRUPO_N.Proveedor SET (LOCK_ESCALATION = TABLE)
GO
COMMIT
BEGIN TRANSACTION
GO
ALTER TABLE GRUPO_N.Ciente ADD
	Saldo numeric(18, 2) NOT NULL CONSTRAINT DF_Ciente_Saldo DEFAULT 10
GO
ALTER TABLE GRUPO_N.Ciente ADD CONSTRAINT
	FK_Ciente_DetalleEntidad FOREIGN KEY
	(
	ID_Detalle
	) REFERENCES GRUPO_N.DetalleEntidad
	(
	ID
	) ON UPDATE  NO ACTION 
	 ON DELETE  NO ACTION 
GO
ALTER TABLE GRUPO_N.Ciente
  RENAME TO GRUPO_N.Cliente;
GO
ALTER TABLE GRUPO_N.Cliente SET (LOCK_ESCALATION = TABLE)
GO
COMMIT
