USE [GD1C2012]
GO

IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[GRUPO_N].[DeleteUser]') AND type in (N'P', N'PC'))
DROP PROCEDURE [GRUPO_N].[DeleteUser]

SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE GRUPO_N.DeleteUser
	@User_ID int
AS
BEGIN
	SET NOCOUNT ON;

	UPDATE GRUPO_N.Usuario SET Activo = 0 WHERE ID = @User_ID
END
GO