USE [GD1C2012]
GO

IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[GRUPO_N].[GetRoles]') AND type in (N'P', N'PC'))
DROP PROCEDURE [GRUPO_N].[GetRoles]

SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

CREATE PROCEDURE [GRUPO_N].[GetRoles]
AS
BEGIN
	SET NOCOUNT ON;
    
	SELECT ID, Descripcion FROM GRUPO_N.Rol
	WHERE Activo = 1
END
GO
